image: gcc:8.3

pipelines:
  default:
    - step:
        script:
          # Dependencies
          - apt update
          - apt install -y python-pip cargo
          - pip install cpplint
          # Run tests
          - TERM=xterm CARGO_TEST_ARGS='-- --skip src/lib.rs' make
