[package]
name = "bidi-codegen"
version = "0.1.0"
authors = ["Lucien Guimier <lucien.guimier@laposte.net>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
quote = "1.0.2"
proc-macro2 = "1.0.1"
